#!/bin/bash
#
# Copyright (c) 2018 Zubax Robotics, zubax.com
# Distributed under the MIT License, available in the file LICENSE.
# Author: Pavel Kirienko <pavel.kirienko@zubax.com>
#

function git_is_clean()
{
    [[ $(git diff --shortstat 2> /dev/null | tail -n1) == "" ]] &&\
    [[ $(git status --porcelain 2>/dev/null| grep "^??" | wc -l) == "0" ]]
}

cat <<EOF
/*
 * AUTOGENERATED, DO NOT EDIT.
 * Generated on `date` by $0
 */

#pragma once

#include <cstdint>

namespace current_build_info
{

static constexpr std::uint32_t VCSCommitID = 0x`git rev-parse --short=8 HEAD`UL;

static constexpr std::uint32_t BuildTimestampUTC = `date --utc +%s`UL;

static constexpr bool BuildIsDirty = `git_is_clean && echo false || echo true`;

}
EOF
